ANNOTATE:
  TRIALS: ['demo']
  MAX_DIST_TO_MESH: 0.15
  FRAME_IDS:
    - 2000
    - 2055
    - 5

CALIBRATION:
  TRIALS: ['demo']
  _X: 4.
  _Y: 4.
  _Z: 3.
  GROUND: 0.
  VOXEL_SPACE: 0.02
  NB_POINTS: 140
  RADIUS: 0.1

VISUALIZE:
  TRIAL: 'demo'
  FRAME_IDS:
    - 2000
    - 2010
    - 5